name: google_maps_place_picker_aki
description: A Flutter plugin which provides 'Picking Place' using Google Maps
  widget. (AKI version)
version: 3.1.3
homepage: https://github.com/nobodyyu/google_maps_place_picker_aki

environment:
  sdk: '>=3.2.3 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  geolocator: ^12.0.0
  google_api_headers: ^4.1.1
  google_maps_flutter: ^2.7.0
  flutter_google_maps_webservices: ^1.1.1
  http: ^1.2.1
  provider: ^6.1.2
  tuple: ^2.0.2
  uuid: ^4.4.0
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null

false_secrets:
  - /example/lib/keys.dart
  - /example/android/app/src/main/AndroidManifest.xml
  - /example/ios/Runner/AppDelegate.swift
